# Generated by Django 4.1 on 2023-07-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImagenLogo', models.ImageField(upload_to='config')),
                ('linkFacebook', models.CharField(max_length=255, verbose_name='Link Facebook')),
                ('linkTwitter', models.CharField(max_length=255, verbose_name='Link Twitter')),
                ('linkYoutube', models.CharField(max_length=255, verbose_name='Link Youtube')),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('horarios', models.TextField()),
            ],
            options={
                'verbose_name': 'Configuración General',
            },
        ),
        migrations.CreateModel(
            name='PaginaPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('Frase', models.CharField(max_length=255)),
                ('Descripcion', models.TextField()),
                ('Imagen', models.ImageField(upload_to='paginaPrincipal')),
            ],
            options={
                'verbose_name': 'Pagina Principal',
            },
        ),
    ]
