# Generated by Django 4.1 on 2023-07-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionGeneral',
        ),
        migrations.DeleteModel(
            name='PaginaPrincipal',
        ),
    ]
