# Generated by Django 4.1 on 2023-07-27 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galeria',
            },
        ),
        migrations.CreateModel(
            name='Sala_Normal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Imagen', models.ImageField(upload_to='Sala_Normal')),
            ],
            options={
                'verbose_name': 'Sala Normal',
                'verbose_name_plural': 'Salas Normales',
            },
        ),
        migrations.CreateModel(
            name='Sala_Transitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Imagen', models.ImageField(upload_to='Sala_Transitoria')),
            ],
            options={
                'verbose_name': 'Sala Transitoria',
                'verbose_name_plural': 'Salas Transitorias',
            },
        ),
        migrations.CreateModel(
            name='SalaInteractiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Imagen', models.ImageField(upload_to='SalaInteractiva')),
            ],
            options={
                'verbose_name': 'Sala Interactiva',
                'verbose_name_plural': 'Salas Interactivas',
            },
        ),
        migrations.CreateModel(
            name='ImagenesGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='ImagenesGaleria')),
                ('Galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_imagenes', to='SALAS.galeria')),
            ],
            options={
                'verbose_name': 'Imágen Galeria',
                'verbose_name_plural': 'Imágenes Galeria',
            },
        ),
    ]
