# Generated by Django 4.1 on 2023-07-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SALAS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesRecorrido_Interactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='ImagenesGaleria')),
            ],
            options={
                'verbose_name': 'Imágen Recorrido Interactivo',
                'verbose_name_plural': 'Imágenes Recorrido Interactivo',
            },
        ),
        migrations.CreateModel(
            name='Recorrido_Interactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Imagen', models.ImageField(upload_to='RecorridoInteractivos')),
            ],
            options={
                'verbose_name': 'Recorrido Interactivo',
                'verbose_name_plural': 'Recorridos Interactivos',
            },
        ),
        migrations.DeleteModel(
            name='SalaInteractiva',
        ),
        migrations.AddField(
            model_name='imagenesrecorrido_interactivo',
            name='Recorrido_Interactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recorrido_Interactivo_imagenes', to='SALAS.recorrido_interactivo'),
        ),
    ]
