# Generated by Django 4.1 on 2023-07-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SALAS', '0002_imagenesrecorrido_interactivo_recorrido_interactivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo_Independiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Imagen', models.ImageField(upload_to='Articulo_Objeto')),
            ],
            options={
                'verbose_name': 'Articulo Independiente',
                'verbose_name_plural': 'Articulos Independiente',
            },
        ),
        migrations.CreateModel(
            name='Vitrina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Imagen', models.ImageField(upload_to='Vitrinas')),
                ('Recorrido_Interactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recorrido_Interactivo_Vitrina', to='SALAS.recorrido_interactivo')),
            ],
            options={
                'verbose_name': 'Vitrina',
                'verbose_name_plural': 'Vitrinas',
            },
        ),
        migrations.CreateModel(
            name='Articulo_Vitrina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Imagen', models.ImageField(upload_to='Articulo_Objeto')),
                ('Vitrina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vitrina_Articulo_Vitrina', to='SALAS.vitrina')),
            ],
            options={
                'verbose_name': 'Articulo Vitrina',
                'verbose_name_plural': 'Articulos Vitrina',
            },
        ),
    ]
