# Generated by Django 4.1 on 2023-07-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SALAS', '0003_articulo_independiente_vitrina_articulo_vitrina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recorrido_interactivo',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.DeleteModel(
            name='Articulo_Vitrina',
        ),
    ]
