# Generated by Django 4.0.2 on 2023-08-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SALAS', '0004_alter_recorrido_interactivo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecorridoVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Video', models.FileField(upload_to='recorrido_virtual')),
            ],
            options={
                'verbose_name': 'Recorrido Virtual',
                'verbose_name_plural': 'Recorridos Virtuales',
            },
        ),
    ]
