# Generated by Django 4.2 on 2023-09-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SALAS', '0005_recorridovirtual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sala_Normal',
        ),
        migrations.AlterModelOptions(
            name='recorrido_interactivo',
            options={'verbose_name': 'Recorrido Interactivo', 'verbose_name_plural': 'Recorridos Interactivos'},
        ),
        migrations.AddField(
            model_name='recorrido_interactivo',
            name='Descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
