# Generated by Django 4.1 on 2023-07-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo_SalaTransitoria', models.CharField(max_length=255, verbose_name='Sala Transitoria')),
                ('Imagen_SalaTransitoria', models.ImageField(upload_to='menuPrincipal', verbose_name='Imagen Sala Transitoria')),
                ('Titulo_DescripcionDeSalas', models.CharField(max_length=255, verbose_name='Descripción DeSalas')),
                ('Imagen_DescripcionDeSalas', models.ImageField(upload_to='menuPrincipal', verbose_name='Imagen Descripción De Salas')),
                ('Titulo_TrabajoInvestigativo', models.CharField(max_length=255, verbose_name='Trabajo Investigativo')),
                ('Imagen_TrabajoInvestigativo', models.ImageField(upload_to='menuPrincipal', verbose_name='Imagen Trabajo Investigativo')),
                ('Titulo_Galeria', models.CharField(max_length=255, verbose_name='Galeria')),
                ('Imagen_Galeria', models.ImageField(upload_to='menuPrincipal', verbose_name='Imagen Galeria')),
                ('Titulo_RecorridoVirtual', models.CharField(max_length=255, verbose_name='Recorrido Virtual')),
                ('Imagen_RecorridoVirtual', models.ImageField(upload_to='menuPrincipal', verbose_name='Imagen Recorrido Virtual')),
                ('Titulo_RecorridoInteractivo', models.CharField(max_length=255, verbose_name='Recorrido Interactivo')),
                ('Imagen_RecorridoInteractivo', models.ImageField(upload_to='menuPrincipal', verbose_name='Imagen Recorrido Interactivo')),
                ('Titulo_JuegosInteractivo', models.CharField(max_length=255, verbose_name='Juegos Interactivo')),
                ('Imagen_JuegosInteractivo', models.ImageField(upload_to='menuPrincipal', verbose_name='Imagen Juegos Interactivo')),
            ],
            options={
                'verbose_name': 'Página Principal',
            },
        ),
    ]
