# Generated by Django 4.0.2 on 2023-08-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0002_menuprincipal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuprincipal',
            options={'verbose_name': 'Menu Principal'},
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='servidor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Servidor'),
        ),
    ]
