# Generated by Django 4.1 on 2023-07-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Imagen', models.ImageField(upload_to='articulos')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Trabajo_Investigativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Imagen', models.ImageField(upload_to='Trabajos Investigativos')),
            ],
            options={
                'verbose_name': 'Trabajo Investigativo',
                'verbose_name_plural': 'Trabajos Investigativos',
            },
        ),
    ]
