# Generated by Django 4.2 on 2023-09-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JUEGOS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Juego',
            new_name='JuegoMarcar',
        ),
    ]
